Update qa-check.yml

diff --git a/.github/workflows/qa-check.yml b/.github/workflows/qa-check.yml
--- a/.github/workflows/qa-check.yml
+++ b/.github/workflows/qa-check.yml
@@ -12,47 +12,50 @@ jobs:
       - uses: actions/checkout@v3
         with:
           ref: ${{ github.ref }}
-          fetch-depth: 0
       
-      - name: Get SHAs
-        id: get_shas
+      - name: Get Branch SHA
+        id: get_branch_sha
         run: |
-          #get last common sha between QA and current branch
-          echo "::set-output name=last-common-sha::$(git merge-base HEAD QA)"
-          git merge-base HEAD QA
-          git merge-base ${{ github.ref }} QA
+          echo "::set-output name=branch-sha::$( ${{ github.event.pull_request.head.sha }})"
+          echo "HEAD SHA: ${{ github.event.pull_request.head.sha }}"
+
+      - uses: actions/checkout@v3
+        with:
+          ref: QA
+          fetch-depth: 0
 
       - name: Compare SHAs
         id: compare-shas
         run: |
-          echo "HEAD SHA: ${{ github.event.pull_request.head.sha }}"
-          echo "Last Common SHA with QA: ${{ steps.get_shas.output.last-common-sha }}"
-          if [ "${{ steps.get_shas.output.last-common-sha }}" != "${{ github.event.pull_request.head.sha }}" ]
-          then
-            echo "::set-output name=pr-message::Did you merge to QA first? HEAD SHA ${{ github.event.pull_request.head.sha }} does not match last common  QA SHA ${{ steps.get_shas.output.last-common-sha }}."
-            echo "::set-output name=passed::false"
-          else
-            echo "::set-output name=pr-message::'Looks like you merged to QA already! HEAD SHA ${{ github.event.pull_request.head.sha }} matches last common QA SHA ${{ steps.get_shas.output.last-common-sha }}."
-            echo "::set-out name=passed::true"
-          fi
+            git merge-base ${{ steps.get_branch_sha.outputs.branch_sha }} QA
+#         run: |
+#           echo "Last Common SHA with QA: ${{ steps.get_shas.output.last-common-sha }}"
+#           if [ "${{ steps.get_shas.output.last-common-sha }}" != "${{ github.event.pull_request.head.sha }}" ]
+#           then
+#             echo "::set-output name=pr-message::Did you merge to QA first? HEAD SHA ${{ github.event.pull_request.head.sha }} does not match last common  QA SHA ${{ steps.get_shas.output.last-common-sha }}."
+#             echo "::set-output name=passed::false"
+#           else
+#             echo "::set-output name=pr-message::'Looks like you merged to QA already! HEAD SHA ${{ github.event.pull_request.head.sha }} matches last common QA SHA ${{ steps.get_shas.output.last-common-sha }}."
+#             echo "::set-out name=passed::true"
+#           fi
           
 
-      - name: Comment on PR
-        uses: mshick/add-pr-comment@v1
-        with:
-          message: |
-            ${{ steps.compare-shas.outputs.pr-message }}
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
-          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
-          allow-repeats: false 
+#       - name: Comment on PR
+#         uses: mshick/add-pr-comment@v1
+#         with:
+#           message: |
+#             ${{ steps.compare-shas.outputs.pr-message }}
+#           repo-token: ${{ secrets.GITHUB_TOKEN }}
+#           repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
+#           allow-repeats: false 
           
-      - name: Pass/Fail
-        run:
-          if [${{ steps.compare-shas.out.passed }}==true]
-          then
-            exit 0
-          else
-            exit 1
-          fi
+#       - name: Pass/Fail
+#         run:
+#           if [${{ steps.compare-shas.out.passed }}==true]
+#           then
+#             exit 0
+#           else
+#             exit 1
+#           fi
 
        
